### ISSUE TITLE
Can't start node server

### ISSUE THREAD

**Issue by shaheero** [savsharma2/loopback-sql-create-model-with-relation#1]
Connection fails: ConnectionError: Failed to connect to 127.0.0.1:1433 - connect ECONNREFUSED 127.0.0.1:1433
It will be retried for the next request.

events.js:160
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Failed to connect to 127.0.0.1:1433 - connect ECONNREFUSED 127.0.0.1:1433
    at Connection.<anonymous> (......../node_modules/loopback-connector-mssql/node_modules/mssql/lib/tedious.js:378:25)
    at Connection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.socketError (......../node_modules/tedious/lib/connection.js:531:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by timvandesteeg** [comment]
Apparently your connection parameters are not correct in **server/datasources.json**
Your database refused the connection
